# Generated by Django 5.1.15 on 2026-02-28 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('danger', 'Critical'), ('success', 'Success')], default='info', max_length=10)),
                ('alert_type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget_type', models.CharField(choices=[('kpi_cards', 'KPI Cards'), ('cash_flow', 'Cash Flow Chart'), ('alert_center', 'Alert Center'), ('quick_actions', 'Quick Actions'), ('executive_summary', 'Executive Summary'), ('revenue_chart', 'Revenue Chart'), ('expense_chart', 'Expense Chart'), ('receivables_aging', 'Receivables Aging'), ('payables_aging', 'Payables Aging')], max_length=50)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('column_span', models.PositiveSmallIntegerField(default=6)),
                ('is_visible', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('user', 'tenant', 'widget_type')},
            },
        ),
    ]
