# Generated by Django 5.1.15 on 2026-03-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('system', 'System Generated'), ('recurring', 'Recurring'), ('allocation', 'Allocation'), ('closing', 'Period Close'), ('ap_payment', 'AP Payment')], default='manual', max_length=20),
        ),
    ]
