# Generated by Django 5.1.15 on 2026-03-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0003_alter_journalentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('system', 'System Generated'), ('recurring', 'Recurring'), ('allocation', 'Allocation'), ('closing', 'Period Close'), ('ap_payment', 'AP Payment'), ('ar_receipt', 'AR Receipt'), ('ar_credit_memo', 'AR Credit Memo'), ('ar_write_off', 'AR Write-Off'), ('cm_transfer', 'Cash Management Transfer'), ('cm_bank_fee', 'Bank Fee')], default='manual', max_length=20),
        ),
    ]
