# Generated by Django 5.1.15 on 2026-03-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0007_alter_journalentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('system', 'System Generated'), ('recurring', 'Recurring'), ('allocation', 'Allocation'), ('closing', 'Period Close'), ('ap_payment', 'AP Payment'), ('ar_receipt', 'AR Receipt'), ('ar_credit_memo', 'AR Credit Memo'), ('ar_write_off', 'AR Write-Off'), ('cm_transfer', 'Cash Management Transfer'), ('cm_bank_fee', 'Bank Fee'), ('fa_acquisition', 'FA Acquisition'), ('fa_depreciation', 'FA Depreciation'), ('fa_disposal', 'FA Disposal'), ('fa_impairment', 'FA Impairment'), ('ic_receipt', 'IC Goods Receipt'), ('ic_adjustment', 'IC Inventory Adjustment'), ('ic_cogs', 'IC Cost of Goods Sold'), ('ic_landed_cost', 'IC Landed Cost'), ('me_intercompany', 'ME Intercompany'), ('me_elimination', 'ME Elimination'), ('me_translation', 'ME Currency Translation'), ('me_gaap_adjust', 'ME GAAP Adjustment'), ('tx_return_payment', 'Tax Return Payment'), ('tx_use_tax', 'Use Tax Accrual'), ('tx_provision', 'Income Tax Provision'), ('tx_audit_adjust', 'Tax Audit Adjustment')], default='manual', max_length=25),
        ),
    ]
